name: Proof HTML
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
  proof:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Proof HTML
        uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./dist
